%{
A function to compute a parking fee, for Regan.

"Let's say you want to park your car in the SNA Airport parking structure,
and you have to select one of the two options of short term parking
(option = 1) or long term parking (option = 2). Here is the details of how
much you will be charged based on each option:
	Option 1: First 20 minutes will cost you $3 and each additional 20 minutes
	(or fraction of 20 minutes) will cost you $1. Daily maximum is $20. Weekly
	maximum is $60.
	Option 2: First hour will cost you $5 and each additional hour (or fraction of
	an hour) will cost you $1. Daily maximum is $20. Weekly maximum is $60."
%}

function total = parkingrate(option, minutes)
	if (option == 1)
		total = parkingrate_helper( ...
			minutes, ...
			20, ...
			3, ...
			1, ...
			20, ...
			60 ...
		);
	elseif (option == 2)
		total = parkingrate_helper( ...
			minutes, ...
			60, ...
			5, ...
			1, ...
			20, ...
			60 ...
		);
	else
		total = -1;
	end
end

function total = parkingrate_helper( ...
	minutes, ...
	minutes_per_charge, ...
	charge_initial, ...
	charge_next, ...
	max_daily, ...
	max_weekly ...
)
	total = 0; day = 0; week = 0;  % Current charges.
	for timestep = 0 : ceil(minutes/minutes_per_charge)-1
		if (mod(timestep, 72) == 0) day = 0; end  % Daily reset.
		if (mod(timestep, 504) == 0) week = 0; end  % Weekly reset.
		if (day < max_daily && week < max_weekly)  % Below maximums?
			if (timestep == 0)
				charge = charge_initial;
			else
				charge = charge_next;
			end
			total = total + charge;
			day = day + charge;
			week = week + charge;
		end
	end
end
